### ISSUE TITLE
[Feature Request] NCurses Interface

### ISSUE THREAD

**Issue by fusir** [evilsocket/opensnitch#1051]
A reverse-firewall that lets you respond as requests go out is a great thing to have.  It sucks that it's only available for desktop linux.  Some basically live in the command line.  It would be really cool to have this level of control over outbound connections in that kind of environment.  I suppose ncurses isn't the only way to go and a more intermediate command line interface could be possible.  A more simple version would break several of the ui roles into separate commands.  Fox example one could catch all of the requests and ask for a simple [Y(es)/n(o)/a(lways)/b(lock permenently)] input.  But a tab-based n-curses interface with the ability to look at existing rules and events all inside the same process would be the most slick.

**Comment by gustavo-iniguez-goya** [comment]
I think this feature has already been requested in #208, #1152 and some other issues.
I wrote something at the start of the year, with github.com/rivo/tview instead of ncurses, but the layout was basically the same than the current GUI, with tabs, etc. We'll see if I can publish something usable .

I'll post any update on the issue #208
