### ISSUE TITLE
Autostart folder getting root permissions with rpm

### ISSUE THREAD

**Issue by sebastianelsner** [evilsocket/opensnitch#1068]
Hello,

Problem:
I just installed the latest release of opensnitch on my Fedora 39 via the Release rpms. The software is working well, but the rpm installer made my users `/home/xxx/.config/autostart` folder belong to `root`. This results in a problem where programs like "Gnome Tweaks" cannot write to it any more and crash.

Solution:
Change the rpm spec file to not include the autostart file. I dont think its possible to give it another user in there?

Regards

Sebastian

**Comment by gustavo-iniguez-goya** [comment]
Noted @sebastianelsner , thank you for report. I'll review it.

**Comment by gustavo-iniguez-goya** [comment]
Tested on OpenSuse TumbleWeed, as well as on Fedora 39. In both cases the ownership of ~/.config/autostart/ is not changed to root.
There must be a particular condition that changes it.

**Comment by gustavo-iniguez-goya** [comment]
Reproduced. The problem occurs when the directory `/home/$user/.config/autostart/` does not exist.

**Comment by TriMoon** [comment]
@gustavo-iniguez-goya , system-wide user services should be placed in `/usr/lib/systemd/user` or as last resort under `/etc/systemd/user` and not under the user's home dir...

**Comment by gustavo-iniguez-goya** [comment]
hey @TriMoon ,

In this case it's not a systemd service, it's the autolaunch of the GUI when a user starts a new session.

**Comment by TriMoon** [comment]
@gustavo-iniguez-goya 
> In this case it's not a systemd service, it's the autolaunch of the GUI when a user starts a new session.

Yes i know that's why you need to put it under the `user` subdir instead of the `system`.
Note the last part of the dir's i mentioned :wink:

**Comment by gustavo-iniguez-goya** [comment]
thank you for the links @TriMoon . Actually I've only played once with systemd user services, but how common are they on the Desktop Environments? just out of curiosity, because as far as I can tell all the distros I've tried are using `.config/autostart` or `/etc/xdg/` to launch user applications. 

The other problem that comes to mind is what to do on non-systemd based systems, like Devuan or Debian when usng sysv.
Right now the autostart the GUI after login feature works an all systems (from ubuntu16/mint 19 to mint 21.3/f39/etc).

By the way, we can discuss these ideas on the Development discussion forum, feel free to open new topics! at least that way they'll be documented.
