### ISSUE TITLE
[Bug] UI Crashing After Update To v1.6.5

### ISSUE THREAD

**Issue by zero77** [evilsocket/opensnitch#1093]
**Describe the bug**
I have updated the daemon an ui and nodes to v1.6.5 and it works but after a while the UI crashis.
I have updated from  v1.6.4

Include the following information:
 - OpenSnitch version. v1.6.5
 - OS: Debian
 - Version sid
 - Window Manager:i3wm
 - Kernel version: 6.6.13-amd64

**To Reproduce**
1. update to  v1.6.5
2. open ui
3. wait for a minute
4. ui crashis
5. See error

**Post error logs:** 
All logs above this looks normal

https://pastebin.com/raw/UEjbSiwQ

**Expected behavior (optional)**

**Screenshots**

**Additional context**

**Comment by gustavo-iniguez-goya** [comment]
problem found. I'll fix it and create a new GUI release.

**Comment by gustavo-iniguez-goya** [comment]
When there're more than 1 node connected the status statistics are not painted, because previously they were painted whenever any node sent them instead of being accumulated and it was not very helpful (and a little bit annoying).

By the way, please, apply this simple fix and let me know if it works: 

in /usr/lib/python3/dist-packages/opensnitch/dialogs/prompt.py , after line 219 add:

            self._peer = peer

As far as I can tell it does.

**Comment by gustavo-iniguez-goya** [comment]
new packages published: https://github.com/evilsocket/opensnitch/releases/tag/v1.6.5.1

closing this issue as fixed.
