### ISSUE TITLE
centos7 install error(opensnitch-1.6.5-1.x86_64)

### ISSUE THREAD

**Issue by p4ulb** [evilsocket/opensnitch#1096]
did anybody try to install the latest version on centos7? 
am trying to install and getting the following error.

any ideas?

![opensnitch](https://github.com/evilsocket/opensnitch/assets/104515428/69264259-6d3f-4625-b007-75479d8042a2)

**Comment by gustavo-iniguez-goya** [comment]
Hi @p4ulb ,

I tested it on centos 7.7, and yum segfaults. Maybe the rpm version used to build it is incompatible with the one of these systems, or there's some incompatible macro in the rpm.

For now what you can do is install it manually:

- unpack the rpm: `rpm2cpio ./opensnitch-1.6.5-1.x86_64.rpm | cpio -idmv `
- copy the files to their location (take a look at the output of rpm2cpio to know where goes what)
- enable the service and start the daemon (`systemctl enable opensnitch; service opensnitch start`)

maybe a package manager agnostic installer wouldn't be a bad idea...

By the way, interesting to see that the main module to intercept connections work. Since it's a 3.10 kernel I didn't expect that :)
Anyway I'd expect some errors, since I haven't tested it on these kernels. If you happen to install and use it, please, report any problem.

**Comment by p4ulb** [comment]
Thanks for getting back to me :)

I've had some python dependency errors that i have manage to correct.

Now im getting the following:
![image](https://github.com/evilsocket/opensnitch/assets/104515428/123e3868-30b1-4bce-934c-3a80b1ef46e7)

**Comment by gustavo-iniguez-goya** [comment]
Did you install the UI with `pip -r install requirements.txt` ? it'll download the dependencies that it's complaining about (grpc, etc).

**Comment by p4ulb** [comment]
Really appreciate your support with this but I am going to upgrade the system.
I am getting a load of dependency errors on python and it just refuses to play ball.

Am moving to rocky9 with my install. Am testing with rocky9 in a VM and it seems to running just fine.

**Comment by p4ulb** [comment]
Really appreciate your support with this but I am going to upgrade the system.
I am getting a load of dependency errors on python and it just refuses to play ball.

Am moving to rocky9 with my install. Am testing with rocky9 in a VM and it seems to running just fine.
