### ISSUE TITLE
Bad UI on HiDPI screens

### ISSUE THREAD

**Issue by melizeche** [evilsocket/opensnitch#22]
In HiDPI screen resolutions(e.g. 3200x1800) the UI is displayed incorrectly
![screenshot from 2017-05-01 21-49-47](https://cloud.githubusercontent.com/assets/484773/25601210/5b91873e-2eb8-11e7-97ce-07a9212e2fc3.png)

**Comment by voltagex** [comment]
http://www.itopen.it/qgis-and-qt-getting-ready-for-hidpi-screens/

From what I've read, QT4 doesn't have particularly good support for HiDPI.

**Comment by hobarrera** [comment]
Any particular reason for using Qt4?

**Comment by evilsocket** [comment]
The original contributor pushed a Qt4 based UI, that's the reaons :P

**Comment by ABaptista** [comment]
I'm not sure, but I read somewhere that if you want to use Qt5 with python2 you need to compile it manually. That's why I used Qt4.
Anyway, I think both versions should be supported, because some people already have pyQt5 installed while others have pyQt4. I noticed that someone already submitted a pull request with this in mind :)
