### ISSUE TITLE
Requirement is not recognized

### ISSUE THREAD

**Issue by Khoramyar** [evilsocket/opensnitch#244]
HI Everyone;

When I try to make, I get:

`  Could not find a version that satisfies the requirement pyqt5==5.10.1 (from -r requirements.txt (line 5)) (from versions: )
No matching distribution found for pyqt5==5.10.1 (from -r requirements.txt (line 5))
`

but I have pyq5 already installed:

` $sudo apt install pyqt5-dev pyqt5-dev-tools 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pyqt5-dev is already the newest version (5.10.1+dfsg-1ubuntu2).
pyqt5-dev-tools is already the newest version (5.10.1+dfsg-1ubuntu2).
The following packages were automatically installed and are no longer required:
  gccgo-8 libgo13
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
`

Any ideas?

**Comment by jonathanvlan** [comment]
the problem is the specific dependencies .
sudo python --version
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7
you need python 3.7 for this package python-pyqt5

There is the available  package with the specific dependencies * opensnitch_1.0.deb
https://sourceforge.net/projects/unknownos/files/opensnitch/ 

you only need to install the necessary from terminal or you can do automatically from gdebi
sudo apt-get install libnetfilter-queue1 libnetfilter-conntrack3 python3-slugify python-pyqt5 libc6 python3.7

Tested on Debian Buster and Kali linux
I do not know if it works on ubuntu,

**Comment by Khoramyar** [comment]
Managed to install it finally. :)
