### ISSUE TITLE
[Feature Request] Extend to Microphone, Speakers and Cam access

### ISSUE THREAD

**Issue by ksthiele** [evilsocket/opensnitch#245]
Hi,

it would be nice if it could be extended to mic-, speaker- and cam access, maybe even natively control it when it's a flatpak or snap app

**Comment by gustavo-iniguez-goya** [comment]
although it's an interesting idea, I think this request is out of scope.

Valid requests, in my opinion, would be adding Yara rules, support for scanning domains with Virus Total (or others services), ads filter lists, alerts by email/pop-ups based on certain patterns, allow to kill processes based on patterns ... etc. This is mainly a network analysis/security tool.

Maybe someone can create a new tool for warning you if a (multimedia) device is accessed :)

**Comment by raboof** [comment]
I agree we should keep the project focused, so not supporting media device access makes sense.

When someone writes an opensnitch-like tool for device access, however, perhaps it could also provide an opensnitch-style gRPC service, so it would be possible to create one unified UI that allows controlling both.

**Comment by GreenLunar** [comment]
Hello friends,
I've found this thread quite by accident.

### Government Approved
Kay's (@ksthiele) idea is good, and, on a second thought, even actual, namely for a couple of reasons:
1) Since the days of Kazza (P2P content transferring program), we've all witnessed a new type of business plan which is spying on people (as users), and that business plan took its position in our world behind legal means, and yet, it's not ethical and it will never be.
2) As of today, all our devices are subjected to government regulation, and one of the main condition most governments require is technical not-publicly-available specifications along with option for backdoors.  Proof to that, is that most of the portable devices sold to us, including routers, have government approved firmware and operating systems that are not always replaceable, and have backdoors.

That option DOES seem to be out of scope, but it makes sense 110% in the current state of affairs.
**Please reopen this thread.**

+1 for @ksthiele


### CDs and DVDs (still in use)
Are you still in doubt?
Think of it, once more...

Do you remember, that in order for us to install a Linux operating system, we needed a Disc?
Today, we need tend to use USB sticks instead, as USB provides use with a much flexible and even more portable solution that DVD-RWs etc.

What does it mean?
People drop burning software applications in favor of applications like [Rufus](https://rufus.ie/) and `dd` command...

In order to make software like [K3b](https://k3b.org/) relevant to those users, they must add support for Live USB creation.

If you're still in doubt, please refer to the [Lumina Desktop Environment](https://lumina-desktop.org/);
Even though it is designed for server and system administrators;
 its [file archiver](https://lumina-desktop.org/features/#file-archiver) has built-in support for burning ISO files into USB devices; and listen to this
 its file manager ([Insight](https://lumina-desktop.org/features/#insight-file-manager)) has built-in support for Git, can you imagine?!
 **a file archiver, intended for server administrator and power-users, is more relevant to the end-user than an advanced and highly reputable Disc Burning solution of The KDE Desktop.** (please read this paragraph once again)

**Comment by GreenLunar** [comment]
Hello friends,
I've found this thread quite by accident.

### Government Approved (a calamity to cybersecurity)
Kay's (@ksthiele) idea is good, and, on a second thought, even actual, namely for a couple of reasons:
1) Since the days of Kazza (P2P content transferring program), we've all witnessed a new type of business plan which is spying on people (as users), and that business plan took its position in our world behind legal means, and yet, it's not ethical and it will never be.
2) As of today, all our devices are subjected to government regulation, and one of the main condition most governments require is technical not-publicly-available specifications along with option for backdoors.  Proof to that, is that most of the portable devices sold to us, including routers, have government approved firmware and operating systems that are not always replaceable, and have backdoors.

That option DOES seem to be out of scope, but it makes sense 110% in the current state of affairs.
**Please reopen this thread.**

+1 for @ksthiele


### CDs and DVDs (still in use)
Are you still in doubt?
Think of it, once more...

Do you remember, that in order for us to install a Linux operating system, we needed a Disc?
Today, we need tend to use USB sticks instead, as USB provides use with a much flexible and even more portable solution that DVD-RWs etc.

What does it mean?
People drop burning software applications in favor of applications like [Rufus](https://rufus.ie/) and `dd` command...

In order to make software like [K3b](https://k3b.org/) relevant to those users, they must add support for Live USB creation.

If you're still in doubt, please refer to the [Lumina Desktop Environment](https://lumina-desktop.org/);
Even though it is designed for server and system administrators;
 its [file archiver](https://lumina-desktop.org/features/#file-archiver) has built-in support for burning ISO files into USB devices; and listen to this
 its file manager ([Insight](https://lumina-desktop.org/features/#insight-file-manager)) has built-in support for Git, can you imagine?!
 **a file archiver, intended for server administrator and power-users, is more relevant to the end-user than an advanced and highly reputable Disc Burning solution of The KDE Desktop.** (please read this paragraph once again)

**Comment by GreenLunar** [comment]
Example story,

Users receives an email from Marketplace website.
The connection to the Marketplace website is whitelisted.
The email features a 2.5 inch HDD with 2GBs (Yes, two Gee Bee) at cost of $20 - Labeled for Car navigation systems.
User open the link and leaves page open.

User's partner walks by and sees the product page.
The partner isn't much aware that today we have MicroSD cards with larger storage capacity for that cost 5$.

Partner, didn't read the description thoroughly, says "That's exactly what I needed"
The sentence of the Partner is received by the Marketplace system.
AI of Marketplace system recognizes the voice and analyses the tone of voice and the whole sentence.

Partner is now targeted and receives an email with a link to the 2GB HDD (can be the same product/link, and can be different but is labeled for Car navigation system).
Partner clicks on the link and buys a low quality product.

Blocking the Marketplace from listening is a good idea.

**Comment by GreenLunar** [comment]
Example story,

User receives an email from Marketplace website.
The connection to the Marketplace website is whitelisted.
The email features a 2.5 inch HDD with 2GBs (Yes, two Gee Bee) at cost of $20 - Labeled for Car navigation systems.
User open the link and leaves page open.

User's partner walks by and sees the product page.
The partner isn't much aware that today we have MicroSD cards with larger storage capacity for that cost 5$.

Partner, didn't read the description thoroughly, says "That's exactly what I needed"
The sentence of the Partner is received by the Marketplace system.
AI of Marketplace system recognizes the voice and analyses the tone of voice and the whole sentence.

Partner is now targeted and receives an email with a link to the 2GB HDD (can be the same product/link, and can be different but is labeled for Car navigation system).
Partner clicks on the link and buys a low quality product.

Blocking the Marketplace from listening is a good idea.
