### ISSUE TITLE
do not sudo pip3 install in Makefile !

### ISSUE THREAD

**Issue by squalou** [evilsocket/opensnitch#291]
Hi,

I just noticed the `sudo pip3 install --upgrade .` in the Makefile.

This will probably cause issues at linux distribution level, you should really never do that.

pip should be used to install dependencies in a virtual_env, never system-wide.

Now ... I don't have the perfect packaging solution at hand.

To explain futher, here's for instance what can be found on Arch distribs :

`community/python-grpcio 1.27.1-1 (1.3 MiB 4.6 MiB) (Installed)`

If you sudo pip3 install it, it will break future system upgrade.

**Comment by CanntAim** [comment]
Pretty sure with python packages that serve as system dependencies you need to be installing them through `apt` in the case of Ubuntu... 

Otherwise you are defeating the entire point of having a distribution _(i.e manage your system dependencies for you)_. This tool may have very well been written to work with specific version of the packages listed in the `requirements.txt` file but really you should allow your users to use the version their system package manager supports rather than forcing them to grab some random one from pypi.

Throwing an idea out there but perhaps using something like tox and testing against a range of possible versions of those packages at least the ones on the `stable` branch of major Linux distributions.

**Comment by SuperSandro2000** [comment]
A correct approach would be to use ``pip3 install --user .``.

**Comment by gustavo-iniguez-goya** [comment]
> Pretty sure with python packages that serve as system dependencies you need to be installing them through apt in the case of Ubuntu...

Unfortunately some python3-grpcio packages does not work with the GUI. [Not even with a simple example](https://stackoverflow.com/questions/65145129/unable-to-get-grpc-server-working-using-python3-grpcio-shipped-with-several-gnu). I'll open an issue on the grpcio repository seeking for help.

On the other hand, python3-grpcio package is not always packaged in some distributions (Ubuntu 18.xx for example, which many people still uses).

I'll remove sudo from the Makefiles.
