### ISSUE TITLE
opensnitch ui not changing to dark mode when my style is "Arch-Dark"

### ISSUE THREAD

**Issue by freddii** [evilsocket/opensnitch#303]
First of all it is a really usefull program :)

**feature request**
At the moment opensnitchs ui is not changing to dark mode when my style is "Arch-Dark".
I like it to change colors when style changes like other programs like freetuxtv or firefox do it.
![dark-bug](https://user-images.githubusercontent.com/7213207/102433290-d8c0c380-4013-11eb-9a7e-1cef92bc27c8.png)

setup:
GTK Theme: Arc-Dark [GTK2]
Icon Theme: Papirus-Dark

**To Reproduce**
In xfce:

sudo apt install arc-theme papirus-icon-theme -y

settings-manager > appearance > Style > Arc Dark
settings-manager > appearance > Icons > Papirus Dark

**Comment by gustavo-iniguez-goya** [comment]
ok, thank you @freddii !

I'll look into it.

**Comment by gustavo-iniguez-goya** [comment]
As far as I can tell, this is a problem of the Desktop Environment and how it handles other kind of graphical tookit different to GTK. You're running a Qt app on a GTK environment, so I guess that this problem is not particular to OpenSnitch, but all Qt apps.

On KDE works as expected when you change to a Dark style theme.

https://www.youtube.com/watch?v=rP4DWu24ff0
https://askubuntu.com/questions/51166/how-to-make-qt-programs-look-good-under-xfce

**Comment by freddii** [comment]
Thanks for your help.
The youtube video instruction fixed it.
In short:
´´
sudo apt-get install -y qt5-style-plugins
sudo cat << EOF | sudo tee  /etc/environment
QT_QPA_PLATFORMTHEME=gtk2
EOF
´´´

**Comment by gustavo-iniguez-goya** [comment]
instructions added to the Known Problems wiki page.

**Comment by Ud4ba** [comment]
This happens only on Gnome?

**Comment by gustavo-iniguez-goya** [comment]
nope, as far as I can tell this problem affects all GTK based Desktop Environments.
To workaround this problem it's planned to add an option to change the style: https://github.com/evilsocket/opensnitch/issues/424#issuecomment-861649310
