### ISSUE TITLE
Display and label destination IP of DNS + domain from DNS query

### ISSUE THREAD

**Issue by benjaoming** [evilsocket/opensnitch#321]
Hi all

I'm a completely new user to OpenSnitch, really liking it.

**Describe the bug**

My first and second prompt looked like this - from Firefox, then from systemd.

![image](https://user-images.githubusercontent.com/374612/103297215-25cf6d00-49f8-11eb-90b8-e0a4b6522e63.png)

I might misunderstand something, but I think the text is wrong?

I would think that systemd-resolved and Firefox were resolving the domain "docs.google.com" (which I made a request for) and not that they connect to it on Port 53.

**To Reproduce**

1. Install 1.3.1 debs on Ubuntu 20.04
2. Run opensnitch-ui

**Post error logs:** 

```
[2020-12-29 15:38:52]  IMP  Start writing logs to %!(EXTRA string=/var/log/opensnitchd.log)
[2020-12-29 16:00:37]  IMP  Added new rule: allow if process.path is '/usr/sbin/avahi-daemon'
[2020-12-29 16:02:20]  IMP  Added new rule: allow if list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/firefox/firefox"}]'
[2020-12-29 16:03:27]  IMP  Added new rule: allow if list is '[{"type": "simple", "operand": "process.path", "data": "/usr/lib/systemd/systemd-resolved"}]'
```

**OS (please complete the following information):**
 - OS: Ubuntu
 - Window Manager: Gnome
 - Kernel version: 5.4.0-58-generic #64-Ubuntu
 - Version 20.04

**Additional context**

Debian packages used.

**Comment by gustavo-iniguez-goya** [comment]
Hi @benjaoming !

Well, yes, the text probably should be "is trying to resolve..." or something similar. Some time ago the text was:

`firefox is connecting to 1.1.1.1 (www.mozilla.com)`

Which is clearer to me (not only clearer, but more correct), but some users complained that they were expecting exactly the text that appears now :)

The text could be personalized on the UI if the destination port is 53. 

However the UI doesn't know the network layer of the connection, so if a DNS query is performed through a different port the text would be as it is now. On the contrary, if a non DNS connection is opened to the port 53 (for whatever reason), we'd display that an app is trying to resolve a domain.

**Comment by benjaoming** [comment]
Hi @gustavo-iniguez-goya - thanks so much for explaining! I agree that the text definitely should be clear and that displaying the domain that is being resolved could be very very helpful.

But when I read the text, I thought that Firefox was somehow sending DNS queries to docs.google.com.

Is there a reference for a previous conversation about the text? Perhaps it can benefit from a bit more tuning :)

**Comment by gustavo-iniguez-goya** [comment]
This is one of the threads: https://github.com/gustavo-iniguez-goya/opensnitch/issues/6

We've discussed it several times on another threads, but as part of other conversations.

**Comment by poetryrose** [comment]
Wouldn't something like:

> process_name is (attempting) to resolve (hostname) via 1.1.1.1 on udp port 53

@gustavo-iniguez-goya I think the distinction should be clear that there is never a "connection" to a UDP port, as this is unequivocally a connection-less protocol, thus language including: "connecting", "connecting to", "opening", "opened", etc. should be avoided at all cost.  Firewalls and protocols are already a bit of a learning curve for non-techie users, so any diligence toward ensuring what folks do end up reading is actually correct, per RFC, etc. would go a long way.

Support for personalization is greatly appreciated, and all techies will hopefully use this where it's supported when needed, but let's not forget about healthy diligence toward correct lingo. :)

Maybe even a small round info icon near UDP would help clear this up with verbosity for users that wish to hover/click for more details on UDP, TCP, etc. when they start to see different protocols in the notifications with different language based on protocol.

@gustavo-iniguez-goya you also mentioned that if DNS queries were being transmitted on a port aside from UDP 53 that there isn't underlying logic to make a determination that it's truly being used for resolution, as well as UDP 53 being used for something outside of DNS.  This leads to defaulting to potentially more misleading and incorrect language. Being clear that something isn't truly known is much more rewarding than hinting that something is being used for resolving a host when there's no underlying confirmation with the packets.  It also seems like a good port to actually use for malicious traffic since the end-user will simply believe it's just dns requests (and potentially whitelist it) since that's what they're being told via the notifications.

With that said, I'm excited to have stumbled upon this project a moment ago while looking for alternatives for LS on Linux. I can't wait to install and potentially help contribute!  You guys rock!

**Comment by benjaoming** [comment]
I think this sounds great and would definitely be an improvement :+1:

> process_name is (attempting) to resolve (hostname) via 1.1.1.1 on udp port 53

**Comment by gustavo-iniguez-goya** [comment]
@themighty1 @xenDE, any thoughts on this request?

![image](https://user-images.githubusercontent.com/2742953/103486037-1fc3fc80-4dfb-11eb-8560-901cbcb6b12c.png)

As mentioned above, the GUI doesn't know if the connection is a DNS request or not. It only knows the destination port.

**Comment by themighty1** [comment]
I agree that "connecting to domain.con on udp port 53" is misleading and should be changed.
I like the wording in the screenshot above.

**Comment by gustavo-iniguez-goya** [comment]
ok! I'll change it

**Comment by gustavo-iniguez-goya** [comment]
Done @benjaoming , thank you for reporting this!
