### ISSUE TITLE
[Feature Request] add more right click options

### ISSUE THREAD

**Issue by NRGLine4Sec** [evilsocket/opensnitch#334]
It could be useful to add more right click options than only the delete one.
List of useful options :
- clone rule
- temporary disable the rule (with the need of a new right click to re-enable it)
- clear hits count (maybe it could be a good idea to clear hits count by default after change a rule)
- show logs matching the rule
- show the rule equivalent in command line (iptables command line)

**Comment by gustavo-iniguez-goya** [comment]
Could you explain some of the feature requests? Only to know what's the use case and get a better idea of the request, (just out of curiosity).

Some notes:

> temporary disable the rule (with the need of a new right click to re-enable it)

the easiest way would be to right click on a rule to disable/enable it. If it's enabled, then the option will be "disable", etc.

options we can add:
 - enable/disable
 - edit
 - delete (already added)
 - clone (duplicate)

> clear hits count (maybe it could be a good idea to clear hits count by default after change a rule)

The hits count is computed on the daemon, the GUI only saves the received data to its DB. Instead of cache statistics on the daemon and send them to the UI every second, we should send them as soon as they happen. But it's a quite intrusive change (i.e.: some things might stop working). Scheduled for the near future.

> show logs matching the rule

if you click on the name of the rule, you see all the connections that matched the rule. 

> show the rule equivalent in command line (iptables command line)

do you mean system (`/etc/opensnitchd&system-fw.json`) of application rules (`/etc/opensnitchd/rules/*`)?

**Comment by NRGLine4Sec** [comment]
Hi @gustavo-iniguez-goya 

> options we can add:
> 
> * enable/disable
> * edit
> * delete (already added)
> * clone (duplicate)

Yes, absolutely.

> > clear hits count (maybe it could be a good idea to clear hits count by default after change a rule)
> 
> The hits count is computed on the daemon, the GUI only saves the received data to its DB. Instead of cache statistics on the daemon and send them to the UI every second, we should send them as soon as they happen. But it's a quite intrusive change (i.e.: some things might stop working). Scheduled for the near future.

Maybe it is not simple as to ask :).
But I like this option that I use already in the Cisco ASDM to manage ASA firewalls. To my mind, it's important to know if the modification of a rule result in the match a the new (changed) rule by the ability to clear hits count. Cisco clear hits count by default after modification in a rule. I like this approach too, but maybe it is a parameter that coulb be configurable to let users do what they want.

> > show logs matching the rule
> 
> if you click on the name of the rule, you see all the connections that matched the rule.

OK sorry for that, I'm used to looking at the logs on the command line..
So this feature is sufficient.

> > show the rule equivalent in command line (iptables command line)
> 
> do you mean system (`/etc/opensnitchd&system-fw.json`) of application rules (`/etc/opensnitchd/rules/*`)?

As for the previous query, I'm more confortable with command line, so I would have the correspondant iptables command line of a rule. It's more covenient for scripting some rules, but if it's not possible, maybe the content of the .JSON file could be sufficient.

**Comment by gustavo-iniguez-goya** [comment]
> But I like this option that I use already in the Cisco ASDM to manage ASA firewalls. To my mind, it's important to know if the modification of a rule result in the match a the new (changed) rule by the ability to clear hits count. Cisco clear hits count by default after modification in a rule. I like this approach too, but maybe it is a parameter that coulb be configurable to let users do what they want.

Some people may want to keep the existing connections logs (I guess). We could add a button to delete the logs of the rule.

>As for the previous query, I'm more confortable with command line, so I would have the correspondant iptables command line of a rule. It's more covenient for scripting some rules, but if it's not possible, maybe the content of the .JSON file could be sufficient.

Some clarification: the rules are not translatable to iptables. iptables nor nftables filter by applications (process path, process command line, etc), we do it on the daemon, and when a rule matches a particular network connection we tell iptables to drop or allow it.

I've been thinking on improving the [cli tool](https://github.com/gustavo-iniguez-goya/opensnitch/tree/cli) (based on we already talked on Discussions), by adding options to change the configuration, rules and firewall from the command line like this:

- `op-cli config -default-action enable -ui-address tcp://172.16.2.13 -method proc -log-file /var/log/op.log -log-level DEBUG`
- `op-cli firewall -status` , `op-cli firewall -disable` , `op-cli firewall -enable`
- `op-cli rules -list`, `op-cli rules -delete <RULE_NAME>`, `op-cli rules -disable <RULE_NAME>`

adding or editing a rule could be done by a simple command line interactive menu, or via parameters:
- `op-cli rules -add <RULE_NAME> -dst-port 80 -proc-path /usr/bin/curl -action deny -uid 0 ...`

The only problem is that cli tool acts as a server, so you can't have 2 UIs running at the same time (GUI and TUI for example). And the daemon (nodes) should know the address of the server (GUI or TUI). It's weird, and not how we're used to use cli tools, but it's how it is right now.

**Comment by NRGLine4Sec** [comment]
> Some people may want to keep the existing connections logs (I guess). We could add a button to delete the logs of the rule.

Add a button to delete the logs is useful but I really would like that the hits count could be re-initilize after modification of a rule. You can keep to don't re-initialize it by default, if it's configurable, therefore I agree with you.

> Some clarification: the rules are not translatable to iptables. iptables nor nftables filter by applications (process path, process command line, etc), we do it on the daemon, and when a rule matches a particular network connection we tell iptables to drop or allow it.

Ohh OK, I completely misunderstood this, thanks a lot for clarification.

> I've been thinking on improving the [cli tool](https://github.com/gustavo-iniguez-goya/opensnitch/tree/cli) (based on we already talked on Discussions), by adding options to change the configuration, rules and firewall from the command line like this:
> 
> * `op-cli config -default-action enable -ui-address tcp://172.16.2.13 -method proc -log-file /var/log/op.log -log-level DEBUG`
> * `op-cli firewall -status` , `op-cli firewall -disable` , `op-cli firewall -enable`
> * `op-cli rules -list`, `op-cli rules -delete <RULE_NAME>`, `op-cli rules -disable <RULE_NAME>`
> 
> adding or editing a rule could be done by a simple command line interactive menu, or via parameters:
> 
> * `op-cli rules -add <RULE_NAME> -dst-port 80 -proc-path /usr/bin/curl -action deny -uid 0 ...`
> 
> The only problem is that cli tool acts as a server, so you can't have 2 UIs running at the same time (GUI and TUI for example). And the daemon (nodes) should know the address of the server (GUI or TUI). It's weird, and not how we're used to use cli tools, but it's how it is right now.


I haven't played with op-cli yet but it looks super cool to me. I will definitely use it. Thanks !!
So I reformulate my request, it could be awesome to have a right click with the correspondant op-cli tool command line of a specific rule :)

**Comment by gustavo-iniguez-goya** [comment]
Summary of the request:

- ~context menu: clone rule~ DONE
- ~context menu: edit rule~ DONE
- ~clicking on a cell selects the row, instead of only a cell.~ DONE
- ~temporary disable the rule (with the need of a new right click to re-enable it)~ DONE
- ~show logs matching the rule~ ALREADY ADDED
- ~show the rule equivalent in command line (iptables command line)~ doesn't apply
- clear hits count (maybe it could be a good idea to clear hits count by default after change a rule) - NOT YET
- copy hosts list - NOT YET

Extras:
Double clicking on a row open the details for that item, instead of clicking on a particular cell.


I'll commit it soon.

>Add a button to delete the logs is useful but I really would like that the hits count could be re-initilize after modification of a rule. You can keep to don't re-initialize it by default, if it's configurable, therefore I agree with you.

If we reinitialize the hits count to 0 after changing a rule, we can't undone it, and maybe some users do not want to reinitalize it. 
However if we default to not delete logs, but let the users clear the logs by clicking on a button, then we cover both situations.

**Comment by gustavo-iniguez-goya** [comment]
I think that all the requests have been added finally.
