### ISSUE TITLE
[Doc request]  Please mention other firewalls and dependencies in install instructions

### ISSUE THREAD

**Issue by BillDietrich** [evilsocket/opensnitch#443]
In general, I think iptables and nftables and eBPF must be installed before installing OpenSnitch, right ?  Maybe all systems have them by default, I don't know.  Maybe get user to do lsmod to see if they're there, do modprobe if they're missing ?

Do I need to turn off or uninstall other firewalling (firewalld, ufw, gufw) before installing OpenSnitch ?  Will the OpenSnitch install or app turn them off automatically ?

What happens if I am using a VPN client that writes its own iptables or nftables rules ?

Please answer these questions in the install instructions or somewhere else appropriate.  Thanks.

**Comment by BillDietrich** [comment]
I see that OpenSnitch is only for outbound traffic, at present.  Inbound controls are under development.  So there will be cases where a user wants to use an inbound firewall (e.g. gufw) and OpenSnitch at same time ?  And in future maybe cases where only OpenSnitch is used.  Please document this.  Thanks.

**Comment by gustavo-iniguez-goya** [comment]
Hi @BillDietrich ,

Ok, I'll answer your questions, and later add them to the FAQ or Install section. Please, if you could rephrase the answers to sound more natural you'd help us a lot :)

> iptables and nftables and eBPF must be installed before installing OpenSnitch, right ?

Yes, OpenSnitch needs iptables (the command) or nftables.

If the command iptables is not installed or it's deprecated (`iptables -V` > `iptables vx.y.z (legacy)`) then nftables will be used. 

If nftables is used we don't rely on any command, we talk directly to the kernel, so the only constraint is that it must be supported in the kernel (`grep NFT /boot/config-$(uname -r)`, nftables was added in kernel 3.13).

On the other hand, the default process monitor method is "proc", which just gets the information from ProcFS (i.e.: `/proc`), so `/proc` directory must be mounted (it's not always the case).

But if you select eBPF as process monitor method , then your kernel must have support for it as well as for Kprobes (`grep /boot/config-$(uname -r)` -> CONFIG_KPROBES=y , or =m). If your kernel is not compiled with eBPF and Kprobes support (or maybe another process is using it..) selecting `ebpf` as proc monitor method will fail with an error (visible on the Preferences dialog).

> Maybe get user to do lsmod to see if they're there, do modprobe if they're missing ?

Instead of executing lsmod, we could read `/boot/config-$(uname -r)` or `/proc/modules`. That would help to output better errors messages when we fail creating the NFQUEUE https://github.com/evilsocket/opensnitch/wiki/Known-problems#opensnitchd-does-not-start

> Do I need to turn off or uninstall other firewalling (firewalld, ufw, gufw) before installing OpenSnitch ? Will the OpenSnitch install or app turn them off automatically ?

No, you don't need to turn off or uninstall other firewalling. We don't turn them off, nor delete their rules. 

If iptables is used: our main rules are added to the default filter table, INPUT chain (`iptables -L INPUT`) and mangle table, OUTPUT chain (`iptables -t mangle -L OUTPUT`)
If nftables is used: we add the same rules, but to our own tables for IPv4 and IPv6 families (`nft list ruleset`)

In both cases: 
- we only delete our rules, leaving intact the rest of rules configured by other firewalls. 
- rules are checked every 30s +-, if they don't exist, they're added again.

> What happens if I am using a VPN client that writes its own iptables or nftables rules ?

The VPN should work. Other users also use VPNs (myself included), and haven't had issues so far (well, we had, but they were fixed).

> So there will be cases where a user wants to use an inbound firewall (e.g. gufw) and OpenSnitch at same time ?

Yes, some users use gufw to block inbound connections. 

However OpenSnitch has limited support for "system firewall rules".

If iptables is used you can add rules to `/etc/opensnitchd/system-fw.json` https://github.com/evilsocket/opensnitch/wiki/System-rules. There's no GUI (yet) to configure these rules, and the json format is about to change to support Policies and nftables.

There's no support for nftables "system rules" yet. In either case, this is experimental, in the sense that the .json format will change and there won't be automatic translation between versions.

**Comment by BillDietrich** [comment]
My attempt at rephrasing:

	# Dependencies:

	1. Rules tables:

	OpenSnitch uses iptables (the command), or nftables (the kernel module)
	to detect new connections and enforce rules on traffic.

	If the command iptables is not installed or it's deprecated
	(iptables -V > iptables vx.y.z (legacy)) then nftables
	(grep NFT /boot/config-$(uname -r)) will be used.

	If neither is present then OpenSnitch will install sccessfully
	but give error message X when run.

	2. Process monitoring

	OpenSnitch needs "proc" / ProcFS / the "/proc" directory tree, or
	eBPF (grep /boot/config-$(uname -r) -> CONFIG_KPROBES=y , or =m)
	to monitor process behavior.

	You select the process monitoring method at run-time in OpenSnitch's Preferences menu.

	If your kernel is not compiled with eBPF and Kprobes support (or maybe
	another process is using it) selecting eBPF as proces monitor method
	will fail with an error (visible on the Preferences dialog).


	# Interaction with other software:

	1. You don't need to turn off or uninstall other firewalling.
	OpenSnitch doesn't turn them off, nor delete their rules.

	If iptables is used: OpenSnitch's main rules are added to the default filter table,
	INPUT chain (iptables -L INPUT) and mangle table, OUTPUT chain (iptables -t mangle -L OUTPUT).

	If nftables is used: OpenSnitch adds the same rules, but to its own tables for IPv4 and IPv6
	families (nft list ruleset).

	In both cases:

		- OpenSnitch only deletes its own rules, leaving intact
		the rest of rules configured by other firewalls.

		- OpenSnitch rules are checked every 30s +-.
		If they don't exist, they're added again.

	2. OpenSnitch should co-exist with VPN clients that write rules in
	iptables or nftables.


	# Inbound vs. Outbound traffic

	Originally, OpenSnitch was written to handle outbound traffic only.
	Soon handling of inbound traffic will be supported too.

	At this time, inbound rules can be added only if you're using iptables,
	and must be added manually, by editing /etc/opensnitchd/system-fw.json
	https://github.com/evilsocket/opensnitch/wiki/System-rules
	There's no GUI (yet) to configure these rules, and the json format is
	about to change to support Policies and nftables.

	There's no support for nftables "system rules" yet.

	In either case (iptables or nftables), this is experimental, in the sense
	that the .json format will change and there won't be automatic translation
	between versions.

**Comment by gustavo-iniguez-goya** [comment]
added to its own page, under the Installation section: https://github.com/evilsocket/opensnitch/wiki/Dependencies-and-how-it-works

I've also added the question about turning off other firewalling to the FAQ, because it gets asked a lot.

Thank you! :heavy_check_mark: done.

**Comment by gustavo-iniguez-goya** [comment]
Again, thank you ver ymch @BillDietrich :)
