### ISSUE TITLE
How to change the installation path of the binary and lib when building / compiling a package?

### ISSUE THREAD

**Issue by vukitoso** [evilsocket/opensnitch#449]
Hello.
After compilation via make and building of the package via checkinstall - binaries are located in /usr/local/bin/ and in /usr/local/lib/.
The goal is to place bin and lib files anywhere but in "/usr/local", for example just in "/usr".
Please tell me how to compile correctly so that the binaries and binaries are not in "/usr/local".
Thx.

**Comment by gustavo-iniguez-goya** [comment]
Hi @vebmaster ,

The installation path is hardcoded right now. The daemon can be placed anywhere, but the configuration files are expected to be found under /etc.

The service file also expects to find the daemon under `/usr/local`.

In order to install it in a different directory than `/usr/local/` follow these steps:
1. Copy `daemon/opensnitchd` to `/usr/bin/`
2. Modify this path: https://github.com/evilsocket/opensnitch/blob/5e56e9033fbab78a17549da421bb8e009b762b02/daemon/opensnitchd.service#L11  to point to `/usr/bin/`

The Makefile could be modified to personalize the install path:
```
ifeq ($(PREFIX),)
    PREFIX=/usr/local
endif

(...)

install:
        @mkdir -p /etc/opensnitchd/rules $(PREFIX)/bin/
        @cp opensnitchd $(PREFIX)/bin/
        (...)    
```

`$ PREFIX=/usr make install`

**Comment by vebmaster** [comment]
> 1. Copy daemon/opensnitchd to /usr/bin/

Thank you. I didn't understand this step.
Should this file be copied after I make "make"? Copy it manually?

**Comment by gustavo-iniguez-goya** [comment]
Yes, after typing "make" a new binary will be created under the daemon/ directory: opensnitchd. That's the file to copy to /usr/bin/
