### ISSUE TITLE
Question: 1.4.0 release date

### ISSUE THREAD

**Issue by v1gnesh** [evilsocket/opensnitch#471]
Hi,

Thanks for this project and all the work everyone has done on this.
A quick question - when can we expect 1.4.0 release to be cut?

**Comment by gustavo-iniguez-goya** [comment]
Hi @v1gnesh ,

I want to commit a few fixes and then I'll release a new RC. That'll probably be the last RC. The fsnotify library is being developed again, so if they add the IN_CLOSE_WRITE event I'll update the dependency version, but I doubt they'll add it soon.

There're also some issues that I'm trying to reproduce (#452, #429, #457) because they looks scary.

So in 3 weeks more or less I guess it'll be ready.

Are you using latest release? What've you have been your experience so far? any problem?

**Comment by v1gnesh** [comment]
Thanks for that response.
Yes, I'm using 1.3.6.
I also see that the screen/lists are not dynamically refreshed in all cases.
Have to move to another tab and come back or some such.
Saw your comment/suggestion to do that in one of the other issues from a while back.
That's fine, not a big deal.

I've also hit that issue where opensnitch is blaming the wrong program for a connection attempt.
Noticed that there is/was an issue here for that.
Hoping process identification will get better with 1.4.0 as it's going to use eBPF and some legacy fallback methods.

In general, it's great to have this capability.
Thank you once again for this excellent work!

**Comment by gustavo-iniguez-goya** [comment]
There has been a lot of improvements in the 1.4.0rc series, feedback on stability would be much appreciated!

> I've also hit that issue where opensnitch is blaming the wrong program for a connection attempt.

What program was it? the next v1.4.0rc4 will include an improvement regarding this issue, but in general using eBPF as the procs monitor method helps to minimize (if not solve at all) the problem.

**Comment by v1gnesh** [comment]
Got a prompt for 1Pw attempting to open a site (a site for which it has a saved cred pair).
Didn't explicitly open that site, but just have it open in a pinned tab in Firefox; and the site does the usual background page updates/refresh.

**Comment by gustavo-iniguez-goya** [comment]
v1.4.0 released!

**Comment by v1gnesh** [comment]
Excellent, thank you!
I had just installed `1.3.6` earlier today.
Will just do `sudo dpkg -i *.deb`, as I saw you said it'll install on top of the old one no problem.
