### ISSUE TITLE
OpenSnitch database location issue

### ISSUE THREAD

**Issue by 6-AND-9** [evilsocket/opensnitch#516]
Hello there again,

After successfully solving the daemon issue, I now have another problem. Namely, with the database. OpenSnitch now works, both the daemon and the UI. When I click on the `Preferences` button and go to the `Database` tab, the database is set to memory. While this is fine in general, I want to avoid answering some of the same prompts for which I simply know that I will allow or block.

But when I change to `File`, I get asked to specify a database file. Now, the problem I have with this is that, theoretically, if I specify a file that is located somewhere in  my `/home` (for example), this file will be easily accessible by any user-installed program, malware or an attacker, which could modify it to allow themselves through OpenSnitch and into my system. AFAIK, OpenSnitch is supposed to have a database somewhere in `/` , where it is difficult to reach by non-systemic programs and services installed on the system.

Is this a bug, a feature, and how can I remedy this problem?

The system is Manjaro Pahvo (Gnome), Wayland.

Thanks,
- A

**Comment by 6-AND-9** [comment]
BTW where should I donate, to you @gustavo-iniguez-goya, or/and to @evilsocket, and where exactly (GitHub/PayPal/Patreon/etc.)?

**Comment by gustavo-iniguez-goya** [comment]
>  this file will be easily accessible by any user-installed program, malware or an attacker, which could modify it to allow themselves through OpenSnitch and into my system

Well, not exactly. They should use the GUI to send the rules to the daemon. Just by modifying the DB file does not update daemon's rules. But I see your point.

Maybe you could run the GUI in a container with a separate storage to save the DB. Instead of using a unix file to connect to the daemon, you could launch the GUI as follow:
`opensnitch-ui --socket [::]:50051` # accept incoming connection on port 50051

And change the daemon configuration:
`"Address": "172.17.0.2:50051"`  # connect to the container's IP 172.17.0.2 on port 50051

In any case, you can save the DB to a directory and remove read and write permissions from group and others.

**Comment by evilsocket** [comment]
@6-AND-9 please donate to @gustavo-iniguez-goya, i just bootstrapped this project ages ago, he's doing all the work from quite some time as you can see from https://github.com/evilsocket/opensnitch/graphs/contributors

**Comment by gustavo-iniguez-goya** [comment]
As explained here https://github.com/evilsocket/opensnitch/issues/516#issuecomment-927130939 , there're multiple options to secure the DB on disk. The easiest would be to save it on a directory with read+write permissions only for your user.
