### ISSUE TITLE
Confused about systemctl status output of opensnitch

### ISSUE THREAD

**Issue by molitona** [evilsocket/opensnitch#518]
I've both nftables and iptables installed. Opensnitch is using nftables wich is verified by "nft list ruleset".
nftables is on version 1:1.0.0-1 on Arch repo.
So, why it says 
> iptables v1.8.7 (nf_tables)

why is says that nftables = iptables v1.8.7 ???

> Sep 25 15:28:59 user opensnitchd[616]: [2021-09-25 14:28:59]  INF  iptables version: [iptables v1.8.7 (nf_tables)
> Sep 25 15:28:59 user opensnitchd[616]: ]
> Sep 25 15:28:59 user opensnitchd[616]: [2021-09-25 14:28:59]  WAR  iptables not available: fw, using nftables instead of iptables ([iptables v1.8.7 (nf_tables)

**Comment by gustavo-iniguez-goya** [comment]
> why is says that nftables = iptables v1.8.7 ???

It's the output of `iptables -V`, which we launch to know iptables version. In your case I think iptables is just a symbolic link to nftables:
```
$ ls -l /usr/sbin/iptables*
lrwxrwxrwx. 1 root root   26 nov 16  2018 /usr/sbin/iptables -> /etc/alternatives/iptables
$ ls -l /etc/alternatives/iptables
lrwxrwxrwx. 1 root root 22 nov 16  2018 /etc/alternatives/iptables -> /usr/sbin/iptables-nft
```

hmm, by the way, what opensnitch version are you using? Because those logs are not present in latest v1.4.0, they were removed in this commit:
https://github.com/evilsocket/opensnitch/commit/ba7c4e1878aeda867c78c855ad7e121af5a07de1#diff-829aa9f2aff28bfd736c5ac80ef65086b39807cfd970bdfb5973c55ff4455516

**Comment by molitona** [comment]
I'm just waiting for aur update.

**Comment by molitona** [comment]
Unfortunately, looks like aur package maintainer forget about opensnitch

**Comment by molitona** [comment]
Believe me, it's by default !

Oct 28, 2021, 17:08 by ***@***.***:

**Comment by molitona** [comment]
@gustavo-iniguez-goya 
what's the diff between reject and deny ?

**Comment by gustavo-iniguez-goya** [comment]
deny will discard the connection, while reject will kill the app's socket.

Denying a connection causes applications to retry it until it timesout. This can cause some problems. Take a look:
https://github.com/evilsocket/opensnitch/commit/8d3540f7f95b40afdd44255ab0ab22ce23cbd333

**Comment by gustavo-iniguez-goya** [comment]
well, I'm closing this issue now. I think it's better to discuss and answer all doubts on the Discussions forums, that way other users will find the information more easily.

**Comment by molitona** [comment]
ok fine, just to complete this talk. When you recommend to use reject instead of Deny ? and why reject isn't shown on pop-up ?

**Comment by gustavo-iniguez-goya** [comment]
Reject is better when you want to increase the performance of an application. For example if you configure to block a list of (ad/malware) domains, the web browser may take a long time to load some web pages because it will wait until the request timeouts (~30s).
In the same manner, if an application connects to a host when you launch it and it's denied by a rule, that application will take ~30s or more to show up.

If you configure a rule to reject connections to those domains, that timeout is avoided and the web pages will load faster, or the application will show up instantly.

> and why reject isn't shown on pop-up ?

it's a matter of space, although I could add a combo box with Reject and Denied action. But the main reason is that it's "experimental", in the sense that it hasn't been tested in all kind of kernels and distros.

**Comment by molitona** [comment]
Thanks a lot !!
