### ISSUE TITLE
[Feature Request] Show URL in prompt

### ISSUE THREAD

**Issue by v1gnesh** [evilsocket/opensnitch#567]
### Summary:
Like in [LuLu](https://github.com/objective-see/LuLu), it would be excellent to have the prompt show URL also.
Then, using regex to block certain type of URLs can be built, I hope.
This is possible, since we're using eBPF packet filtering, right?

**Comment by gustavo-iniguez-goya** [comment]
> This is possible, since we're using eBPF packet filtering, right?

It's possible but no because of eBPF. We use `libnetfilter_queue` to intercept connections, and eBPF to get the PID of every connection. On the other hand, extracting URLs from packages, while not a complicated task, needs that someone actually code it. But it's not in my TODO list.

> using regex to block certain type of URLs can be built

Right now what you can do is block malware/ads/trackers/etc domains (v1.4.x and v1.5.0), IPs and network ranges (only in v1.5.x): https://github.com/evilsocket/opensnitch/wiki/block-lists

**Comment by v1gnesh** [comment]
Ah ok, thanks for your response.
