### ISSUE TITLE
opensnitch-ui doesn't start

### ISSUE THREAD

**Issue by molitona** [evilsocket/opensnitch#568]
**Describe the bug**
When launch opensnitch-ui, it doesn't start.

Include the following information:
 - OpenSnitch 1.4.0.r25.689c83f-1 (git version from AUR)
 - OS: ArchLinux
 - Window Manager: GNOME
 - Kernel version: 5.15.8-arch1-1

1. open terminal
2. type opensnitch-ui

**Post error logs:** 
λ ~/ opensnitch-ui
Traceback (most recent call last):
  File "/usr/bin/opensnitch-ui", line 22, in <module>
    from opensnitch.service import UIService
ModuleNotFoundError: No module named 'opensnitch'

**Comment by gustavo-iniguez-goya** [comment]
Hi @molitona , 

Please, ask AUR maintainer about that error, they'll probably help you out better than me with that problem.
Anyway, review also installation logs.

**Comment by molitona** [comment]
I installed opensnitch pkg which is the most updated version now for arch.
I got that prompt when opening ui, what's the matter ?
![e](https://user-images.githubusercontent.com/35532337/146603866-dbfb2fe3-e479-490c-8569-b4f291e5ab01.png)

**Comment by gustavo-iniguez-goya** [comment]
The daemon and the GUI are at different versions, maybe you mixed up package installations? I have no idea since I haven't created that package, so please, review what packages you installed (be sure that the daemon and the GUI are at the same level) and contact AUR package maintainer. Or ask on the Arch forums.

v1.5.x is the current development version, while v1.4.x only receive bug fixes.

**Comment by molitona** [comment]
Haven't mixed anything. It's opensitch AUR pkg installation.
BTW, can it cause problems ?

**Comment by gustavo-iniguez-goya** [comment]
Yes, it can cause problems. v1.5.0 daemon version contain changes that might be incompatible with v1.4.0 GUI.

Closing since this is not an opensnitch error.
