### ISSUE TITLE
OpenSnitch UI does not start minimized

### ISSUE THREAD

**Issue by Frereneo** [evilsocket/opensnitch#764]
**Describe the bug**
Hello, to begin with, thank you for designing OpenSnitch.
If I come to you, it is to point out that OpenSnitch does not start minimized on my system (Fedora 36 - Gnome 42.4)

Include the following information:
 - OpenSnitch 1.5.2
 - OS: Fedora
 - Version: 36
 - Window Manager: GnomeShell 42.4
 - Kernel version: 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
Start the system, and OpenSnitch opens with the main window. whereas on my Ubuntu system, it runs in the background.

Just start the system

**Post error logs:** 
No crash

If the daemon doesn't start:
The daemon starts correctly

If the deb or rpm packages fail to install:
No failed install

thank you for your help
Sincerely,

**Comment by gustavo-iniguez-goya** [comment]
Hi @Frereneo !

You need to install the extension https://extensions.gnome.org/extension/615/appindicator-support/

Try it and let me know if it fixes the issue.

**Comment by Frereneo** [comment]
Hi @gustavo-iniguez-goya,
Thank you very much for your help, it works perfectly.
Knowing that Gnome wants to see this feature disappear, do you have in mind to run OpenSnitch in the background without this extension?
Thank you once again?
Sincerely,

**Comment by gustavo-iniguez-goya** [comment]
hey @Frereneo , sorry for the delayed response. Even if Gnome killed this feature some time ago, I don't think they'll kill extensions, so I guess that for the time being we're safe on this regard.

Anyway, the problem is that the GUI is (mainly) composed of 4 components:
 - a server (to receive and store daemons events: service.py+database.py+nodes.py+utils.py)
 - the icon tray (service.py)
 - a prompt dialog (dialog/prompt.py)
 - and a global GUI (dialog/stats.py, dialog/firewall*.py dialog/ruleseditor*.py, notifications.py)

It'd be better to have at least the server and the GUI separated. The server would run continuously in background (just as the daemon) receiving and storing  events from daemons. That way, we could launch the GUI to connect to the server without having to kill it.

As an extra, it'd allow us to have more GUIs (like a web gui for example).

That said, maybe we could have a wrapper to launch the GUI if it's not running, or bring the GUI to the front: `xdotool search --onlyvisible --class opensnitch-ui windowactivate`

**Comment by Frereneo** [comment]
Hi @gustavo-iniguez-goya ,thanks for the detailed answer :).
I'm from the old school, I don't like to manage my services on a web browser :p.
But if your application migrates to a web browser management I would still stay on this wonderful tool :)
For the moment, I'll just use the extension which works great.
Sincerely,
