### ISSUE TITLE
Nit: 1.6.0-rc.4-1 Pop up UI window, the x for reject is not an icon (yet allow is an icon)

### ISSUE THREAD

**Issue by BetweenTheKeyboardAndChair** [evilsocket/opensnitch#823]
Nit: for 1.6.0-rc.4-1.  In the pop up window, I get a grey x next to reject, and a green check next to allow.  I'd expect both to be colored icons, or neither.    

(Reject is a great feature.  Thank you!)

I'm set to the system theme.  In the settings, UI tab, I do get a warning of "Themes not available.  Install qt-material; pip3 install qt-material"  I do expect the default theme to work without doing additional installs.

Ubuntu 20.4.1 LTS.

**Comment by gustavo-iniguez-goya** [comment]
Hi @BetweenTheKeyboardAndChair , in this case the X is the icon of your system theme. If your system or theme doesn't have that icon in particular, we use the Qt's built-ins icons which you can see here:

![image](https://user-images.githubusercontent.com/2742953/215713651-3967a3f0-e387-4735-8da3-601bb18297a4.png)

The Reject icon is "window-close" as defined here: https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names

The warning is only for opensnitch specific themes.

**Comment by BetweenTheKeyboardAndChair** [comment]
Hi Gustavo,

I looked at  https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html#names, and did not see any mention of reject.  The window-close icon is stated as "The icon used for the “Close Window” item in the application's “Windows” menu." I would not think of this rejection as a close window action.  It is not closing the dialog.

I just checked how the close window icon looks in open snitch using several common icon sets. IMO they all looked pretty bad.  See the image below, which happens to be adwaita.  May I suggest something other than the system close window icon be used?  Maybe one of:
SP_DialogCloseButton
SP_DialogCancelButton
SP_BrowserStop
If you are looking for a standard icon, what about the network-error icon?

![opensnitch](https://user-images.githubusercontent.com/84645709/215718292-594dedf2-ac97-41a1-a577-95b9d9b8adfe.jpg)

This is a nit.  It looked like an unfinished beta UI issue.  I've seen other great products fail because the UI didn't look clean. People saw them and assumed the products were either not finished or not supported or not professional quality.  I'd hate for this to slow down the adoption of opensnitch. It is great.

Thank you for your time and effort.

**Comment by gustavo-iniguez-goya** [comment]
Yes, there's no default icon for reject. However the icon for network-error I think is not suitable in this situation, it's more intended for network-connectivity-error, take a look: `find /usr/share/icons -name 'network-error*'`

HighContrast 48x48:
![image](https://user-images.githubusercontent.com/2742953/215759787-ce306129-d41d-4151-bcca-e3b39cdfddc4.png)

gnome/Adwaita 48x48 (legacy):
![image](https://user-images.githubusercontent.com/2742953/215760019-4480d466-f7fd-4331-8598-48c6316fbddb.png)

Adwaita:
![image](https://user-images.githubusercontent.com/2742953/215760281-60ac40e4-41a6-4114-9da0-30469ce60c0b.png)

 I agree with you, SP_DialogCloseButton, SP_DialogCancelButton or SP_BrowserStopThe would be better options.

The counterpart of those icons on other themes could be edit-delete:
![image](https://user-images.githubusercontent.com/2742953/215761791-b328d4f8-565b-4b04-8a42-01f16efbb4e0.png)

process-stop (actually more because of the name):
![image](https://user-images.githubusercontent.com/2742953/215762070-d547fe2a-bcec-4f2d-8ff9-f982deb91a4b.png)

and use any of the three SP_* built-in icons as fallback.

**Comment by BetweenTheKeyboardAndChair** [comment]
Either of the edit-delete or process-stop icons would be fine.  My preference for the fallback icons, in order would be: SP_BrowserStop, SP_DialogCancelButton, SP_DialogCloseButton.

Thank you.
