### ISSUE TITLE
[Feature Request] Rephrase package description

### ISSUE THREAD

**Issue by petterreinholdtsen** [evilsocket/opensnitch#825]
### Summary:
At the moment the github package description reads "OpenSnitch is a GNU/Linux port of the Little Snitch application firewall".  But the word port implies the same source code is used, and as far as I know the Little Snitch application is non-free software and this is a reimplementation of the same idea.  I suggest to rephrase the description to make this more clear, for example "OpenSnitch is a GNU/Linux licensed interactive application network firewall, similar to Little Snitch on MacOSX."

**Comment by gustavo-iniguez-goya** [comment]
Some more alternatives:

"OpenSnitch is a GNU/Linux interactive application network firewall"
"OpenSnitch is a GNU/Linux interactive application network firewall inspired by LittleSnitch"?

**Comment by grawlinson** [comment]
It looks like [Debian](https://packages.debian.org/search?suite=all&searchon=names&keywords=opensnitch) describe it as `GNU/Linux firewall application`, which is inline with the suggestions so far.

**Comment by Flimm** [comment]
I agree. A _port_ implies that the developers took the software of Little Snitch for macOS and worked on it until it the software worked on Linux. I'm certain that this would be a violation of copyright law, in most cases. [According to Wikipedia](https://en.wikipedia.org/wiki/Porting):
> In software engineering, porting is the process of adapting software for the purpose of achieving some form of execution in a computing environment that is different from the one that a given program (meant for such execution) was originally designed for (e.g., different CPU, operating system, or third party library). The term is also used when software/hardware is changed to make them usable in different environments.

Another word I've seen used is _[clone](https://en.wikipedia.org/wiki/Video_game_clone)_. But I don't think that word would be suitable for OpenSnitch either, as I don't think OpenSnitch feels silimar enough to Little Snitch to justify the name "clone":

I would propose something like:

> OpenSnitch is a firewall application for GNU/Linux, inspired by Little Snitch

I like the comparison with Little Snitch, as it does help me understand what OpenSnitch is meant for, since I am familiar with Little Snitch. It also helps people find OpenSnitch.

**Comment by gustavo-iniguez-goya** [comment]
I just realized that I cannot change the github description. @evilsocket hey, what do you think?
The idea is to change "OpenSnitch is a GNU/Linux port of the Little Snitch application firewall" by any of:

"OpenSnitch is a GNU/Linux licensed interactive application network firewall, similar to Little Snitch on MacOSX."
"OpenSnitch is a GNU/Linux interactive application network firewall"
"OpenSnitch is a GNU/Linux interactive application network firewall inspired by LittleSnitch"

**Comment by evilsocket** [comment]
hey @gustavo-iniguez-goya i'm open to any of them, let me know which one you pick and I'll change the description 👍🏻

**Comment by gustavo-iniguez-goya** [comment]
ok, let's use "OpenSnitch is a GNU/Linux interactive application firewall inspired by LittleSnitch"

**Comment by evilsocket** [comment]
done 👍🏻

**Comment by gustavo-iniguez-goya** [comment]
Thank you !

**Comment by Flimm** [comment]
Nitpick: "Little Snitch" has a space between "Little" and "Snitch".
