### ISSUE TITLE
tag for release 1.6.0?

### ISSUE THREAD

**Issue by kcning** [evilsocket/opensnitch#917]
Hello, I saw the 1.6.0 version bump. If the release is ready, would you mind creating a tag? It'd be very helpful for packaging.
Thank you in advance!

**Comment by gustavo-iniguez-goya** [comment]
Hi @kcning ,

It's almost ready. There aren't significant bugs as far as I can tell, but I still need to work a little bit on the system firewall feature. Improve the GUI mostly.

**Comment by dcarosone** [comment]
(I'm putting this here, rather than in its own issue, since the next release is imminent and will probably make any historical catchup irrelevant)

There's some inconsistency in release publication that I'd like to see avoided going forward.

In the wiki homepage, there's a table listing versions in many packaging systems. My particular interest is nixpkgs:
![image](https://github.com/evilsocket/opensnitch/assets/11495017/03a8d823-fd99-447f-a9d5-e19054ab599b)

This lists 1.5.2 as the version currently packaged (correct) in red as an outdated release.

However, on the project home and releases list, 1.5.2 is listed as the current release.  
![image](https://github.com/evilsocket/opensnitch/assets/11495017/83e5a321-0ef6-40cc-8162-a468cbaa5a8a)

The later 1.5.x don't appear, though some 1.6 pre-releases do. Depending how the distro projects are tracking and getting notified of updates, they may be missing some as a result.  It would be really good to have a consistent release process that ensures whatever is getting missed here happens for all releases so they have the best chance of getting packages promptly updated downstream,
