### ISSUE TITLE
Douane app

### ISSUE THREAD

**Issue by xavier83** [evilsocket/opensnitch#93]
Hope this project isn't re-inventing [Douane](https://github.com/Douane/Douane). If not any argument on why prefer this?

**Comment by evilsocket** [comment]
> Hope this project isn't re-inventing Douane.

Why not? Diversity is a good thing.

> any argument on why prefer this?

Not really, we're just having fun hacking code together and considering different approaches to the same problems Douane is facing.

**Comment by tianon** [comment]
I'm neither a contributor nor maintainer here (just someone interested in the project trying to follow the development), but figured maybe it'd be useful to drop a note as to why I'm interested in what's being built here and am not already using Douane.

When I evaluated Douane (admittedly a little while back), it was not easy to build/run (and packages were sparse), didn't have a lot of granularity (simply "Allow/Deny" vs the wealth of configurability Little Snitch for OSX offered), and required a custom kernel module.

**Comment by xavier83** [comment]
@evilsocket I appreciate diversity of course and commend this project. Honestly I haven't even tried Douane but just heard of it, just wanted a comparison of sort on how opensnitch does better where Dounae falls short. And thanks @tianon

**Comment by evilsocket** [comment]
@xavier83 it's still to early to say that IMO, OpenSnitch is still in a prototype phase.

**Comment by dreamcat4** [comment]
Hey the douane project auther has fixed it's major crashing bug now. There is recent activity on that project and it's worth checking again. And maybe trying if you want. It may still crash every few hours and freeze the whole PC.

The way to install it is remove the line `douane` from `/etc/modules` so that it's kernel module does not automatically load at startup. Then `sudo modprobe douane` when you want to load it.

Otherwise for OpenSnitch then Gustavo's fork is also currently active https://github.com/gustavo-iniguez-goya/opensnitch/releases
