### ISSUE TITLE
Correct process identified but wrong application name+icon

### ISSUE THREAD

**Issue by planetoryd** [evilsocket/opensnitch#956]
Include the following information:
- 1.6.0rc5
 - Version Ubuntu 23.04
 - Window Manager kde
 - Kernel version: Linux 6.2.0-20-generic SMP PREEMPT_DYNAMIC Thu Apr  6 07:48:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I updated the ebpf as you said, and I am running 1.6.0rc5

**It is a UI problem, this time, not the same bug.** The database has correct data (no existence of blender process, recorded, at all). 

It happens consistently

![2023-06-03_00-45](https://github.com/evilsocket/opensnitch/assets/68096727/e0e311a0-4501-44e1-8228-84a5d7a0ada1)

The log level was on `important`, so nothing valuable was recorded. I have database set to in-memory.

**Comment by akronym0** [comment]
I also noticed this "visual" bug. Flatpak only.

**Comment by gustavo-iniguez-goya** [comment]
is it random? or is there a flatpak that I can use to reproduce this issue?

**Comment by planetoryd** [comment]
I installed it by APT.

**Comment by gustavo-iniguez-goya** [comment]
@akronym0 , could you post a flatpak that I can use to reproduce this issue?

**Comment by akronym0** [comment]
> @akronym0 , could you post a flatpak that I can use to reproduce this issue?

I don't think, this is caused by one specific flatpak app.

When you update flatpak apps, flatpak tries to connect to a flatpak server. Opensnitch is able to intercept that connection attempt.

On Linux Mint 21.1 cinnamon Opensnitch intercepts these two calls (right after a reboot, because I set the duration to "until reboot"):

`[/usr/bin/flatpak] flatpak install -y --system flathub `

`[/usr/bin/python3.10] flatpak-update-worker`

During the first call, Opensnitch is trying to find an application/name for the pop-up. And in my case it finds the name of VSCodium (a flatpak app). In the case of the OP, it finds the Blender app. But VSCodium is not a running process at all.

The rule is stored correctly, though. There is no reference to VSCodium in the flatpak rule.

In order to reproduce this, you could try a distro with a flatpak environment and automatic flatpak updates, for example, Linux Mint 21.1 Cinnamon.

**Comment by gustavo-iniguez-goya** [comment]
thank you @akronym0 , reproduced with `flatpak update`.
I'll analyze what's going on.

**Comment by gustavo-iniguez-goya** [comment]
The problem is the `Exec=` field of the .desktop file. For example:

`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community`

When the GUI is launched, we read all the *.desktop files and extract the absolute path to the binary from the Exec= field, and store it to look for it later when an app tries to access the internet.
Later when blender, librewolf or just  `flatpak update` tries to access the internet, we get the binary that opened the connection, and try to find the icon for it. As all the flatpak apps are started with `/usr/bin/flatpak` , we return the latest icon we added to the cache.

`Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=librewolf --file-forwarding io.gitlab.librewolf-community`
and
`~ $ flatpak update`

have the same absolute path to the binary: `/usr/bin/flatpak`

I'll find a solution for this problem.

**Comment by gustavo-iniguez-goya** [comment]
@akronym0 @planetoryd I think this issue could be fixed with this commit https://github.com/evilsocket/opensnitch/commit/173e61b65a0c6a17f108c933029b87741d0cbc37 . 

You can try it by downloading the file https://github.com/evilsocket/opensnitch/blob/master/ui/opensnitch/desktop_parser.py and copying it to /usr/lib/python3/opensnitch/

Now running flatpak plain commands should display a terminal icon, while if you launch a flatpak application it should display the icon. It's maybe not 100% bulletproof, you' ll tell.

Reopen the issue if you find a flatpak app that doesn't display the icon.
